apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atp-router-secrets
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: atp-router-secret
    creationPolicy: Owner
  data:
  - secretKey: database-url
    remoteRef:
      key: prod/atp/database
      property: url
  - secretKey: api-key
    remoteRef:
      key: prod/atp/api
      property: key
  - secretKey: jwt-secret
    remoteRef:
      key: prod/atp/auth
      property: jwt_secret
