apiVersion: apps/v1
kind: Deployment
metadata:
  name: atp-router
spec:
  template:
    spec:
      containers:
      - name: router
        envFrom:
        - configMapRef:
            name: atp-config
        - secretRef:
            name: atp-secrets
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: atp-config
