
server: { http_listen_port: 3200 }
distributor: { receivers: { otlp: { protocols: { grpc: {}, http: {} } } } }
storage: { trace: { backend: local, local: { path: /tmp/tempo } } }
compactor: { compaction: { compaction_window: 1h } }
